package main

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	mrand "math/rand"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func parseCID(output string) string {
	for _, line := range strings.Split(output, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "cid:") {
			return strings.TrimSpace(strings.TrimPrefix(line, "cid:"))
		}
	}
	return ""
}

func contains(slice []string, s string) bool {
	for _, v := range slice {
		if v == s {
			return true
		}
	}
	return false
}

func shorten(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

func findProjectRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return "."
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "."
}

func cmdTestdata(args []string) error {
	fs := flagNewSet("testdata")
	outDir := fs.String("out", "./testdata-gen", "output directory")
	nFiles := fs.Int("files", 10, "number of files to generate")
	nDirs := fs.Int("dirs", 3, "number of subdirectories")
	minSize := fs.Int("min", 1024, "minimum file size in bytes")
	maxSize := fs.Int("max", 65536, "maximum file size in bytes")
	seed := fs.Int64("seed", time.Now().UnixNano(), "random seed")
	if err := fs.Parse(args); err != nil {
		return err
	}

	rng := mrand.New(mrand.NewSource(*seed))

	if err := os.MkdirAll(*outDir, 0755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	dirs := []string{*outDir}
	for i := 0; i < *nDirs; i++ {
		name := fmt.Sprintf("dir%02d_%s", i, randomName(rng, 4))
		path := filepath.Join(*outDir, name)
		if err := os.MkdirAll(path, 0755); err != nil {
			return err
		}
		dirs = append(dirs, path)
	}

	for i := 0; i < *nFiles; i++ {
		dir := dirs[rng.Intn(len(dirs))]
		name := fmt.Sprintf("file%03d_%s.bin", i, randomName(rng, 6))
		path := filepath.Join(dir, name)

		size := *minSize + rng.Intn(*maxSize-*minSize+1)
		data := make([]byte, size)
		rand.Read(data)
		if err := os.WriteFile(path, data, 0644); err != nil {
			return err
		}
	}

	manifestPath := filepath.Join(*outDir, "MANIFEST.txt")
	f, err := os.Create(manifestPath)
	if err != nil {
		return err
	}
	defer f.Close()
	fmt.Fprintf(f, "Generated by drings-deploy testdata\n")
	fmt.Fprintf(f, "seed:  %d\n", *seed)
	fmt.Fprintf(f, "files: %d\n", *nFiles)
	fmt.Fprintf(f, "dirs:  %d\n", *nDirs)
	fmt.Fprintf(f, "time:  %s\n", time.Now().UTC().Format(time.RFC3339))

	nonce := make([]byte, 8)
	rand.Read(nonce)
	os.WriteFile(filepath.Join(*outDir, "hello.txt"), []byte(fmt.Sprintf(
		"hello from data-rings testdata generator\nnonce: %s\ntime: %s\n",
		hex.EncodeToString(nonce), time.Now().UTC().Format(time.RFC3339))), 0644)

	total := countFiles(*outDir)
	fmt.Printf("Generated %d files in %s (%d subdirs)\n", total, *outDir, *nDirs)
	return nil
}

func randomName(rng *mrand.Rand, n int) string {
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, n)
	for i := range b {
		b[i] = chars[rng.Intn(len(chars))]
	}
	return string(b)
}

func countFiles(dir string) int {
	count := 0
	filepath.Walk(dir, func(_ string, fi os.FileInfo, _ error) error {
		if fi != nil && !fi.IsDir() {
			count++
		}
		return nil
	})
	return count
}
