package testrig

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"
)

var (
	localBuildOnce	sync.Once
	daemonBinPath	string
	cliBinPath	string
	localBuildErr	error
)

func buildLocalBinaries(t *testing.T) {
	t.Helper()
	localBuildOnce.Do(func() {
		binDir := filepath.Join(RepoRoot(), ".testbin")
		os.MkdirAll(binDir, 0755)

		daemonBinPath = filepath.Join(binDir, "drings-daemon")
		cmd := exec.Command("go", "build", "-o", daemonBinPath, "./cmd/drings-daemon")
		cmd.Dir = RepoRoot()
		out, err := cmd.CombinedOutput()
		if err != nil {
			localBuildErr = fmt.Errorf("build drings-daemon: %w\n%s", err, out)
			return
		}

		cliBinPath = filepath.Join(binDir, "drings")
		cmd = exec.Command("go", "build", "-o", cliBinPath, "./cmd/drings")
		cmd.Dir = RepoRoot()
		out, err = cmd.CombinedOutput()
		if err != nil {
			localBuildErr = fmt.Errorf("build drings: %w\n%s", err, out)
		}
	})
	if localBuildErr != nil {
		t.Fatalf("local backend: %v", localBuildErr)
	}
}

type localProc struct {
	dataDir		string
	apiPort		int
	dhtPort		int
	cmd		*exec.Cmd
	cancel		context.CancelFunc
	bootstrap	string
	logFile		*os.File
	logPath		string
}

type localBackend struct {
	t		*testing.T
	procs		map[string]*localProc
	mu		sync.Mutex
	logDir		string
	fleetConfigPath	string
	extraDaemonArgs	[]string
}

func NewLocalBackend(t *testing.T) *localBackend {
	t.Helper()
	buildLocalBinaries(t)
	logDir, err := os.MkdirTemp("", "drings-logs-*")
	if err != nil {
		t.Fatalf("create log dir: %v", err)
	}
	t.Logf("[local] daemon logs: %s", logDir)

	return &localBackend{t: t, procs: make(map[string]*localProc), logDir: logDir}
}

func (b *localBackend) LogDir() string	{ return b.logDir }

func (b *localBackend) FleetConfigPath() string	{ return b.fleetConfigPath }

func (b *localBackend) writeFleetConfig(t *testing.T, nodes []*TestNode) {
	t.Helper()
	b.mu.Lock()
	defer b.mu.Unlock()

	var buf strings.Builder
	buf.WriteString("# Auto-generated by testrig local backend. Use with:\n")
	buf.WriteString("#   ./drings-deploy --config " + filepath.Join(b.logDir, "test-fleet.toml") + " <command>\n\n")

	for _, n := range nodes {
		lp := b.procs[n.Name_]
		if lp == nil {
			continue
		}
		fmt.Fprintf(&buf, "[[instances]]\n")
		fmt.Fprintf(&buf, "  name = %q\n", n.Name_)
		fmt.Fprintf(&buf, "  ipv4 = \"127.0.0.1\"\n")
		fmt.Fprintf(&buf, "  local = true\n")
		fmt.Fprintf(&buf, "  api_port = %d\n", lp.apiPort)
		fmt.Fprintf(&buf, "  log_file = %q\n", lp.logPath)
		fmt.Fprintf(&buf, "  data_dir = %q\n", lp.dataDir)
		fmt.Fprintf(&buf, "\n")
	}

	configPath := filepath.Join(b.logDir, "test-fleet.toml")
	if err := os.WriteFile(configPath, []byte(buf.String()), 0644); err != nil {
		t.Logf("[local] warning: could not write fleet config: %v", err)
		return
	}
	b.fleetConfigPath = configPath
	t.Logf("[local] fleet config: %s", configPath)
	t.Logf("[local] use: ./drings-deploy --config %s <command>", configPath)
}

func (b *localBackend) Setup(t *testing.T, nodes []*TestNode, state StartState) {
	t.Helper()
	b.mu.Lock()
	for _, lp := range b.procs {
		if lp.cancel != nil {
			lp.cancel()
			lp.cmd.Wait()
		}
	}
	b.procs = make(map[string]*localProc)
	b.mu.Unlock()

	if len(nodes) > 0 && nodes[0].Cluster_ != nil {
		b.extraDaemonArgs = nodes[0].Cluster_.DaemonArgs
	}

	baseAPIPort := 17400
	baseDHTPort := 17000
	bootstrapAddr := fmt.Sprintf("/ip4/127.0.0.1/tcp/%d", baseDHTPort)

	for i, n := range nodes {
		dataDir, err := os.MkdirTemp("", fmt.Sprintf("drings-%s-*", n.Name_))
		if err != nil {
			t.Fatalf("create data dir for %s: %v", n.Name_, err)
		}
		t.Cleanup(func() { os.RemoveAll(dataDir) })

		identPath := filepath.Join(dataDir, "identity")
		if err := os.WriteFile(identPath, []byte(n.Identity.PrivKeyHex), 0600); err != nil {
			t.Fatalf("write identity for %s: %v", n.Name_, err)
		}

		lp := &localProc{dataDir: dataDir, apiPort: baseAPIPort + i, dhtPort: baseDHTPort + i}
		if i == 0 {
			lp.bootstrap = ""
		} else {
			lp.bootstrap = bootstrapAddr
		}

		b.mu.Lock()
		b.procs[n.Name_] = lp
		b.mu.Unlock()

		b.startDaemon(t, n.Name_, lp)
	}

	b.writeFleetConfig(t, nodes)
}

func (b *localBackend) startDaemon(t *testing.T, name string, lp *localProc) {
	t.Helper()
	ctx, cancel := context.WithCancel(context.Background())
	lp.cancel = cancel

	args := []string{
		"--no-config",
		"--data-dir", lp.dataDir,
		"--api-addr", fmt.Sprintf(":%d", lp.apiPort),
		"--dht-addr", fmt.Sprintf("/ip4/0.0.0.0/tcp/%d", lp.dhtPort),
		"--advertise", "127.0.0.1",
		"--dht-replication", "3",
		"--dht-stabilize", "500ms",
		"--dht-fix-fingers", "300ms",
		"--dht-check-pred", "1s",
		"--mount=false",
		"--debug",
		"--no-publish",
		"--no-background-stabilize",
	}
	if lp.bootstrap != "" {
		args = append(args, "--bootstrap", lp.bootstrap)
	} else {
		args = append(args, "--bootstrap", "none")
	}
	args = append(args, b.extraDaemonArgs...)

	lp.logPath = filepath.Join(b.logDir, name+".log")
	logFile, err := os.Create(lp.logPath)
	if err != nil {
		t.Fatalf("[local] create log file for %s: %v", name, err)
	}
	lp.logFile = logFile

	cmd := exec.CommandContext(ctx, daemonBinPath, args...)

	cmd.Cancel = func() error { return cmd.Process.Signal(syscall.SIGTERM) }
	cmd.WaitDelay = 5 * time.Second
	cmd.Stdout = logFile
	cmd.Stderr = logFile
	if err := cmd.Start(); err != nil {
		t.Fatalf("[local] start %s: %v", name, err)
	}
	lp.cmd = cmd
	t.Cleanup(func() {
		cancel()
		cmd.Wait()
		logFile.Close()
	})

	deadline := time.Now().Add(15 * time.Second)
	for time.Now().Before(deadline) {
		conn, err := net.DialTimeout("tcp", fmt.Sprintf("127.0.0.1:%d", lp.apiPort), time.Second)
		if err == nil {
			conn.Close()
			t.Logf("[local] %s ready on :%d (dht :%d)", name, lp.apiPort, lp.dhtPort)
			return
		}
		time.Sleep(200 * time.Millisecond)
	}
	t.Fatalf("[local] %s API port %d not reachable after 15s", name, lp.apiPort)
}

func (b *localBackend) CreatePrivateRing(t *testing.T, nodes []*TestNode, groupName string) string {
	t.Helper()
	out, err := b.Exec(nodes[0], "ring", "create")
	if err != nil {
		t.Fatalf("[local] ring create on %s: %v\n%s", nodes[0].Name_, err, out)
	}
	groupKey := ParseGroupKey(out)
	if groupKey == "" {
		t.Fatalf("[local] could not parse group-key: %s", out)
	}
	for i, n := range nodes {
		t.Logf("[local] %s joining %s (%d/%d)", n.Name_, groupName, i+1, len(nodes))
		out, err := b.Exec(n, "ring", "join", groupKey, groupName)
		if err != nil {
			t.Errorf("[local] %s join failed: %v\n%s", n.Name_, err, out)
		}
	}
	return groupKey
}

func (b *localBackend) apiURL(n *TestNode) string {
	b.mu.Lock()
	lp := b.procs[n.Name_]
	b.mu.Unlock()
	return fmt.Sprintf("http://127.0.0.1:%d", lp.apiPort)
}

func (b *localBackend) PublicState(n *TestNode) (NodeState, error) {
	resp, err := http.Get(b.apiURL(n) + "/debug/state")
	if err != nil {
		return NodeState{}, fmt.Errorf("node %s: %w", n.Name_, err)
	}
	defer resp.Body.Close()
	var s NodeState
	if err := json.NewDecoder(resp.Body).Decode(&s); err != nil {
		return NodeState{}, fmt.Errorf("node %s: decode: %w", n.Name_, err)
	}
	return s, nil
}

func (b *localBackend) PrivateState(n *TestNode, groupName string) (PrivateRingEntry, bool) {
	resp, err := http.Get(b.apiURL(n) + "/debug/groups")
	if err != nil {
		return PrivateRingEntry{}, false
	}
	defer resp.Body.Close()
	var entries []PrivateRingEntry
	if err := json.NewDecoder(resp.Body).Decode(&entries); err != nil {
		return PrivateRingEntry{}, false
	}
	for _, e := range entries {
		if e.Name == groupName || strings.HasPrefix(e.GroupID, groupName) {
			return e, true
		}
	}
	return PrivateRingEntry{}, false
}

func (b *localBackend) Exec(n *TestNode, args ...string) (string, error) {
	b.mu.Lock()
	lp := b.procs[n.Name_]
	b.mu.Unlock()
	apiAddr := fmt.Sprintf("http://127.0.0.1:%d", lp.apiPort)
	cmdArgs := append([]string{"-api", apiAddr}, args...)
	cmd := exec.Command(cliBinPath, cmdArgs...)
	out, err := cmd.CombinedOutput()
	return strings.TrimSpace(string(out)), err
}

func (b *localBackend) Stop(n *TestNode) error {
	b.mu.Lock()
	lp := b.procs[n.Name_]
	b.mu.Unlock()
	if lp == nil || lp.cancel == nil {
		return nil
	}
	lp.cancel()
	lp.cmd.Wait()
	lp.cancel = nil
	lp.cmd = nil
	return nil
}

func (b *localBackend) Start(n *TestNode) error {
	b.mu.Lock()
	lp := b.procs[n.Name_]
	b.mu.Unlock()
	if lp == nil {
		return fmt.Errorf("node %s has no local proc entry", n.Name_)
	}
	b.startDaemon(b.t, n.Name_, lp)
	return nil
}

func (b *localBackend) StoreFile(n *TestNode, data []byte, group string) (string, error) {
	tmpDir, err := os.MkdirTemp("", "drings-store-*")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(tmpDir)
	fp := filepath.Join(tmpDir, "testdata.bin")
	if err := os.WriteFile(fp, data, 0644); err != nil {
		return "", err
	}
	out, err := b.Exec(n, "add", fp)
	if err != nil {
		return "", fmt.Errorf("add: %w\n%s", err, out)
	}
	cidStr := ParseCID(out)
	if cidStr == "" {
		return "", fmt.Errorf("could not parse CID from add output: %s", out)
	}
	if group != "" {
		out, err = b.Exec(n, "pub", group, cidStr)
		if err != nil {
			return cidStr, fmt.Errorf("pub (private): %w\n%s", err, out)
		}
	} else {
		out, err = b.Exec(n, "pub", cidStr)
		if err != nil {
			return cidStr, fmt.Errorf("pub (public): %w\n%s", err, out)
		}
	}
	return cidStr, nil
}

func (b *localBackend) AddLocal(n *TestNode, data []byte) (string, error) {
	tmpDir, err := os.MkdirTemp("", "drings-add-*")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(tmpDir)
	fp := filepath.Join(tmpDir, "testdata.bin")
	if err := os.WriteFile(fp, data, 0644); err != nil {
		return "", err
	}
	out, err := b.Exec(n, "add", fp)
	if err != nil {
		return "", fmt.Errorf("add: %w\n%s", err, out)
	}
	cidStr := ParseCID(out)
	if cidStr == "" {
		return "", fmt.Errorf("could not parse CID from add output: %s", out)
	}
	return cidStr, nil
}

func (b *localBackend) StoreFileWithTTL(n *TestNode, data []byte, group string, ttl string) (string, error) {
	tmpDir, err := os.MkdirTemp("", "drings-store-*")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(tmpDir)
	fp := filepath.Join(tmpDir, "testdata.bin")
	if err := os.WriteFile(fp, data, 0644); err != nil {
		return "", err
	}
	out, err := b.Exec(n, "add", fp)
	if err != nil {
		return "", fmt.Errorf("add: %w\n%s", err, out)
	}
	cidStr := ParseCID(out)
	if cidStr == "" {
		return "", fmt.Errorf("could not parse CID from add output: %s", out)
	}
	if group != "" {
		out, err = b.Exec(n, "pub", group, cidStr, "--ttl", ttl)
		if err != nil {
			return cidStr, fmt.Errorf("pub (private, ttl=%s): %w\n%s", ttl, err, out)
		}
	} else {
		return cidStr, fmt.Errorf("TTL is only supported for private ring pushes")
	}
	return cidStr, nil
}

func (b *localBackend) FetchCID(n *TestNode, cidStr string, group string) error {
	var args []string
	if group != "" {
		args = []string{"get", group, cidStr}
	} else {
		args = []string{"get", cidStr}
	}
	out, err := b.Exec(n, args...)
	if err != nil {
		return fmt.Errorf("fetch: %w\n%s", err, out)
	}
	return nil
}

func (b *localBackend) ForceStabilize(n *TestNode) error {
	resp, err := http.Post(b.apiURL(n)+"/debug/stabilize", "", nil)
	if err != nil {
		return fmt.Errorf("node %s: %w", n.Name_, err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusNoContent {
		return fmt.Errorf("node %s: stabilize returned %d", n.Name_, resp.StatusCode)
	}
	return nil
}

func (b *localBackend) ForceStabilizePrivate(n *TestNode, groupRef string) error {
	resp, err := http.Post(b.apiURL(n)+"/debug/groups/"+groupRef+"/stabilize", "", nil)
	if err != nil {
		return fmt.Errorf("node %s: %w", n.Name_, err)
	}
	resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound {
		return fmt.Errorf("node %s: group %q not found", n.Name_, groupRef)
	}
	if resp.StatusCode != http.StatusNoContent {
		return fmt.Errorf("node %s: stabilize private returned %d", n.Name_, resp.StatusCode)
	}
	return nil
}

func (b *localBackend) WaitForReplicationDrain(n *TestNode, timeout time.Duration) error {
	url := fmt.Sprintf("%s/debug/replication-drain?timeout=%s", b.apiURL(n), timeout)

	cli := &http.Client{Timeout: timeout + 5*time.Second}
	resp, err := cli.Post(url, "", nil)
	if err != nil {
		return fmt.Errorf("node %s: %w", n.Name_, err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusNoContent {
		return fmt.Errorf("node %s: replication-drain returned %d", n.Name_, resp.StatusCode)
	}
	return nil
}

func (b *localBackend) RepublishSelf(n *TestNode) error {
	resp, err := http.Post(b.apiURL(n)+"/public/peer/publish", "", nil)
	if err != nil {
		return fmt.Errorf("node %s: %w", n.Name_, err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusNoContent {
		return fmt.Errorf("node %s: republish returned %d", n.Name_, resp.StatusCode)
	}
	return nil
}

func (b *localBackend) DeleteRecord(n *TestNode, keyHex string) error {
	req, err := http.NewRequest(http.MethodDelete, b.apiURL(n)+"/debug/records/"+keyHex, nil)
	if err != nil {
		return fmt.Errorf("node %s: %w", n.Name_, err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return fmt.Errorf("node %s: %w", n.Name_, err)
	}
	resp.Body.Close()
	return nil
}

func (b *localBackend) HasRecord(n *TestNode, keyHex string) (bool, error) {
	resp, err := http.Get(b.apiURL(n) + "/debug/records/" + keyHex)
	if err != nil {
		return false, fmt.Errorf("node %s: %w", n.Name_, err)
	}
	defer resp.Body.Close()
	var result struct {
		Found bool `json:"found"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return false, fmt.Errorf("node %s: decode: %w", n.Name_, err)
	}
	return result.Found, nil
}

func (b *localBackend) HasBlock(n *TestNode, cidStr string) (bool, error) {
	resp, err := http.Get(b.apiURL(n) + "/debug/blocks/" + cidStr)
	if err != nil {
		return false, fmt.Errorf("node %s: %w", n.Name_, err)
	}
	defer resp.Body.Close()
	var result struct {
		Found bool `json:"found"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return false, fmt.Errorf("node %s: decode: %w", n.Name_, err)
	}
	return result.Found, nil
}

func (b *localBackend) RecordKeys(n *TestNode) ([]string, error) {
	resp, err := http.Get(b.apiURL(n) + "/debug/records")
	if err != nil {
		return nil, fmt.Errorf("node %s: %w", n.Name_, err)
	}
	defer resp.Body.Close()
	var keys []string
	if err := json.NewDecoder(resp.Body).Decode(&keys); err != nil {
		return nil, fmt.Errorf("node %s: decode: %w", n.Name_, err)
	}
	return keys, nil
}

func (b *localBackend) DeleteBlock(n *TestNode, cidStr string) error {
	req, err := http.NewRequest(http.MethodDelete, b.apiURL(n)+"/debug/blocks/"+cidStr, nil)
	if err != nil {
		return fmt.Errorf("node %s: %w", n.Name_, err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return fmt.Errorf("node %s: %w", n.Name_, err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusNoContent {
		return fmt.Errorf("node %s: delete block returned %d", n.Name_, resp.StatusCode)
	}
	return nil
}

func (b *localBackend) DeleteCID(n *TestNode, cidStr string, group string) error {
	out, err := b.Exec(n, "delete-cid", group, cidStr)
	if err != nil {
		return fmt.Errorf("delete-cid: %w\n%s", err, out)
	}
	return nil
}

func (b *localBackend) HasNetworkBlock(n *TestNode, cidStr string) (bool, error) {
	resp, err := http.Get(b.apiURL(n) + "/debug/network-blocks/" + cidStr)
	if err != nil {
		return false, fmt.Errorf("node %s: %w", n.Name_, err)
	}
	defer resp.Body.Close()
	var result struct {
		Found bool `json:"found"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return false, fmt.Errorf("node %s: decode: %w", n.Name_, err)
	}
	return result.Found, nil
}

func (b *localBackend) NetworkBlockCIDs(n *TestNode) ([]string, error) {
	resp, err := http.Get(b.apiURL(n) + "/debug/network-blocks")
	if err != nil {
		return nil, fmt.Errorf("node %s: %w", n.Name_, err)
	}
	defer resp.Body.Close()
	var result struct {
		Count	int		`json:"count"`
		CIDs	[]string	`json:"cids"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("node %s: decode: %w", n.Name_, err)
	}
	return result.CIDs, nil
}

func (b *localBackend) NetworkRoots(n *TestNode) ([]string, error) {
	resp, err := http.Get(b.apiURL(n) + "/debug/network-roots")
	if err != nil {
		return nil, fmt.Errorf("node %s: %w", n.Name_, err)
	}
	defer resp.Body.Close()
	var result struct {
		Count	int		`json:"count"`
		Roots	[]string	`json:"roots"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("node %s: decode: %w", n.Name_, err)
	}
	return result.Roots, nil
}

func (b *localBackend) RingNetworkBlockCIDs(n *TestNode, ringID string) ([]string, error) {
	resp, err := http.Get(b.apiURL(n) + "/debug/rings/" + ringID + "/network-blocks")
	if err != nil {
		return nil, fmt.Errorf("node %s: %w", n.Name_, err)
	}
	defer resp.Body.Close()
	var result struct {
		Ring	string		`json:"ring"`
		Count	int		`json:"count"`
		CIDs	[]string	`json:"cids"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("node %s: decode: %w", n.Name_, err)
	}
	return result.CIDs, nil
}

func (b *localBackend) RingNetworkRoots(n *TestNode, ringID string) ([]string, error) {
	resp, err := http.Get(b.apiURL(n) + "/debug/rings/" + ringID + "/network-roots")
	if err != nil {
		return nil, fmt.Errorf("node %s: %w", n.Name_, err)
	}
	defer resp.Body.Close()
	var result struct {
		Ring	string		`json:"ring"`
		Count	int		`json:"count"`
		Roots	[]string	`json:"roots"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("node %s: decode: %w", n.Name_, err)
	}
	return result.Roots, nil
}

func (b *localBackend) DataDir(n *TestNode) string {
	b.mu.Lock()
	defer b.mu.Unlock()
	if lp := b.procs[n.Name_]; lp != nil {
		return lp.dataDir
	}
	return ""
}

func (b *localBackend) RestartOnNewPort(n *TestNode, newDHTPort, newAPIPort int) error {
	if err := b.Stop(n); err != nil {
		return fmt.Errorf("stop %s: %w", n.Name_, err)
	}
	b.mu.Lock()
	lp := b.procs[n.Name_]
	if lp == nil {
		b.mu.Unlock()
		return fmt.Errorf("%s: no proc entry", n.Name_)
	}
	lp.dhtPort = newDHTPort
	lp.apiPort = newAPIPort
	b.mu.Unlock()
	b.startDaemon(b.t, n.Name_, lp)
	return nil
}

func (b *localBackend) RingStorage(n *TestNode, ringID string) (int64, int64, error) {
	resp, err := http.Get(b.apiURL(n) + "/debug/rings/" + ringID + "/storage")
	if err != nil {
		return 0, 0, fmt.Errorf("node %s: %w", n.Name_, err)
	}
	defer resp.Body.Close()
	var result struct {
		Used	int64	`json:"used_bytes"`
		Max	int64	`json:"max_bytes"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return 0, 0, fmt.Errorf("node %s: decode: %w", n.Name_, err)
	}
	return result.Used, result.Max, nil
}

func (b *localBackend) Close() error {
	b.mu.Lock()
	defer b.mu.Unlock()
	for _, lp := range b.procs {
		if lp.cancel != nil {
			lp.cancel()
			lp.cmd.Wait()
		}
		if lp.logFile != nil {
			lp.logFile.Close()
		}
	}
	return nil
}

func (b *localBackend) NodeLogPath(name string) string {
	b.mu.Lock()
	lp := b.procs[name]
	b.mu.Unlock()
	if lp == nil {
		return ""
	}
	return lp.logPath
}

func (b *localBackend) NodeLogs(name string) (string, error) {
	path := b.NodeLogPath(name)
	if path == "" {
		return "", fmt.Errorf("no log file for %s", name)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

func (b *localBackend) NodeLogsTail(name string, n int) (string, error) {
	content, err := b.NodeLogs(name)
	if err != nil {
		return "", err
	}
	lines := strings.Split(content, "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.Join(lines, "\n"), nil
}

func (b *localBackend) NodeLogsSince(name string, since, until time.Time) (string, error) {
	return b.NodeLogs(name)
}
